name: Build and Deploy

on:
  push:
    branches:
      - gh-action

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false

    - name: Install Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: 1.6

    - run: |
        julia -e '
          using Pkg;
          Pkg.add(Pkg.PackageSpec(name="Plots"));
          using Plots;
          Pkg.add(Pkg.PackageSpec(name="PlutoSliderServer"));
          using PlutoSliderServer;
          export_directory(Export_output_dir="build");'

    - name: Write dummy file
      run: echo 'Hello, World!' > build/index.md

    - name: Build and deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build

